# Generated by Django 3.2.9 on 2021-11-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_auto_20211119_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Address1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Address2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='AdminNote',
            field=models.TextField(default='Not Added', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Aligners',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ArchForm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Clinic',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='DentistNote',
            field=models.TextField(default='Not Added', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Distalize',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Email',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Expension',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Hint1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Hint2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Hint3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='IPR',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Impression',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='InternalStatus',
            field=models.CharField(default='On', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='LoverMidline',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='LowerJaw',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='OralScan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Overbite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Overjet',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PCrossbite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Photo1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Photo2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Photo3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Photo4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Prescriber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Procline',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Review', 'Review'), ('Decline', 'Decline'), ('On-Hold', 'On-Hold')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Telephone',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Treatment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='TreatmentInPast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='TreatmentLimit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='TreatmentRequired',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='UpperJaw',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='UpperMidline',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
