# Generated by Django 3.2.9 on 2021-12-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_auto_20211119_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='labwork',
            name='TC',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
