# Generated by Django 3.2.9 on 2021-12-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_labwork_tc'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='RepeatStatus',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
