# Generated by Django 4.0.1 on 2022-01-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0008_repeat_expense'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repeat_Expense',
            new_name='RepeatExpense',
        ),
    ]
