# Generated by Django 4.0.1 on 2022-03-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0010_repeatincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
