# Generated by Django 4.0.1 on 2022-04-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0014_alter_patientproposedtreatment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Aligners',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ArchForm',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Distalize',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Expension',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Hint1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Hint2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Hint3',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='IPR',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='LoverMidline',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Overbite',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Overjet',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PCrossbite',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Procline',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Review', 'Review'), ('Decline', 'Decline'), ('On-Hold', 'On-Hold')], default='Pending', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Treatment',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='TreatmentLimit',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='TreatmentRequired',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='UpperMidline',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patientproposedtreatment',
            name='Invoice',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patientproposedtreatment',
            name='ProposedTreatment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patientproposedtreatment',
            name='ThreeDViewProposed',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
