# Generated by Django 4.0.1 on 2022-04-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0016_alter_patient_status_patientbox1'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='box1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
