# Generated by Django 4.0.1 on 2022-04-08 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolioApp', '0018_patient_box2_alter_patient_box1_patientbox2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientproposedtreatment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
