# Generated by Django 4.0.1 on 2022-04-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0020_patient_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='box1',
            new_name='LowerArch',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='box2',
        ),
        migrations.AddField(
            model_name='patient',
            name='upperArch',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patientbox1',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientbox2',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Action',
            field=models.CharField(choices=[('In progress', 'In progress'), ('TC', 'TC')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Progress',
            field=models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Review', 'Review'), ('Decline', 'Decline'), ('On-Hold', 'On-Hold'), ('New', 'New')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Stage',
            field=models.CharField(choices=[('File sent', 'File sent'), ('Model prod', 'Model prod'), ('Aligner prod', 'Aligner prod'), ('Ready', 'Ready')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Status',
            field=models.CharField(choices=[('3D', '3D'), ('Ready', 'Ready')], default='Pending', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Treatment',
            field=models.CharField(choices=[('TREATMENT PLAN: includes 3D visualisation and STL files to print models in house', 'TREATMENT PLAN: includes 3D visualisation and STL files to print models in house'), ('Full TREATMENT: including 3D and all set of aligners', 'Full TREATMENT: including 3D and all set of aligners')], max_length=150, null=True),
        ),
    ]
