# Generated by Django 4.0.1 on 2022-04-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0021_rename_box1_patient_lowerarch_remove_patient_box2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbox1',
            name='stage11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientbox1',
            name='stage12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientbox1',
            name='stage13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientbox1',
            name='stage14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientbox1',
            name='stage15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientbox2',
            name='stage11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientbox2',
            name='stage12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientbox2',
            name='stage13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientbox2',
            name='stage14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientbox2',
            name='stage15',
            field=models.BooleanField(default=False),
        ),
    ]
