# Generated by Django 4.0.1 on 2022-04-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0022_patientbox1_stage11_patientbox1_stage12_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientBox1',
            new_name='LowerArchBox',
        ),
        migrations.RenameModel(
            old_name='PatientBox2',
            new_name='UpperArchBox',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='upperArch',
            new_name='UpperArch',
        ),
    ]
