# Generated by Django 4.0.1 on 2022-04-11 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0023_rename_patientbox1_lowerarchbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowerarchbox',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.patient'),
        ),
        migrations.AlterField(
            model_name='upperarchbox',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.patient'),
        ),
    ]
