# Generated by Django 4.0.1 on 2022-04-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0024_alter_lowerarchbox_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='LowerArchBox',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='UpperArchBox',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
