# Generated by Django 4.0.1 on 2022-04-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0025_patient_lowerarchbox_patient_upperarchbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='LowerArchBox',
            new_name='LowerArchMaterial',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='UpperArchBox',
            new_name='UpperArchMaterial',
        ),
    ]
